BoxLayoutExample:

<BoxLayoutExample>
    orientation: "vertical"
    Button:
        text: "button1"
    Button:
        text: "button2"
    Label:
        text: "label1"


<MainWidget>:
    Button:
        text: "Hello"
        size: "40dp", "40dp"
        pos: "100dp", "200dp"
        color: 0, 0, 1, 1
    Label:
        text: "Label"
        size: "40dp", "40dp"
        pos: "140dp", "240dp"
        color: 1, 0, 0, 1